version: "3.7"

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   volumes: 
  #     - ./frontend/:/app
  #   restart: unless-stopped

  # backend: 
  #   container_name: backend
  #   image: docker-spring-boot-postgres:latest
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/testdb
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=123
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dbprak
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

